# Generated by Django 4.1 on 2025-02-14 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
